name: CI

on: [push, pull_request]

env:
  toolchain-version: 14.3.rel1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: psf/black@stable
        with:
          options: --check --diff --preview
          src: scripts

      - uses: isort/isort-action@master
        with:
          sortPaths: scripts

      - uses: py-actions/flake8@v2
        with:
          path: scripts

      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: scripts

  build:
    runs-on: ubuntu-latest
    name: build-${{ matrix.board }}
    strategy:
      fail-fast: false
      matrix:
        board: [pi3-64, pi4-64, pi5]
    steps:
      - uses: actions/checkout@v4

      - name: Fetch submodules
        run: make submodules

      - uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ env.toolchain-version }}-${{ matrix.board }}

      - name: Cache ARM toolchains
        id: cache-toolchains
        uses: actions/cache@v4
        with:
          path: |
            ~/arm-gnu-toolchain-${{ env.toolchain-version }}-x86_64-arm-none-eabi
            ~/arm-gnu-toolchain-${{ env.toolchain-version }}-x86_64-aarch64-none-elf
          key: cache-arm-toolchains-${{ env.toolchain-version }}

      - name: Install toolchains
        if: steps.cache-toolchains.outputs.cache-hit != 'true'
        run: |
          for triplet in arm-none-eabi aarch64-none-elf; do
            wget -q https://developer.arm.com/-/media/Files/downloads/gnu/${{ env.toolchain-version }}/binrel/arm-gnu-toolchain-${{ env.toolchain-version }}-x86_64-${triplet}.tar.xz
            tar -xf arm-gnu-toolchain-${{ env.toolchain-version }}-x86_64-${triplet}.tar.xz -C ~
            rm arm-gnu-toolchain-${{ env.toolchain-version }}-x86_64-${triplet}.tar.xz
          done

      - name: Update PATH
        run: |
          mkdir ~/ccache_bin
          for triplet in arm-none-eabi aarch64-none-elf; do
            ln -s $(which ccache) ~/ccache_bin/${triplet}-gcc
            ln -s $(which ccache) ~/ccache_bin/${triplet}-g++
            echo "$HOME/ccache_bin:$HOME/arm-gnu-toolchain-${{ env.toolchain-version }}-x86_64-${triplet}/bin" >> $GITHUB_PATH
          done

      - name: Build
        run: make -j BOARD=${{ matrix.board }}

      - name: Build (HDMI console)
        run: make clean && make -j BOARD=${{ matrix.board }} HDMI_CONSOLE=1
